namespace ETicaretAPI.Infrastructure.Operations
{
    public static class NameOperation
    {
        public static string CharacterRegulatory(string name)

          => name.Replace("\"", "")
                .Replace("!", "")
                .Replace("'", "")
                .Replace("^", "")
                .Replace("+", "")
                .Replace("%", "")
                .Replace("&", "")
                .Replace("/", "")
                .Replace("(", "")
                .Replace(")", "")
                .Replace("(", "")
                .Replace("=", "")
                .Replace("?", "")
                .Replace("_", "")
                .Replace("@", "")
                .Replace("`", "")
                .Replace("~", "")
                .Replace(",", "")
                .Replace(":", "")
                .Replace(";", "")
                .Replace(".", "-")
                .Replace("Ö", "O")
                .Replace("ö", "o")
                .Replace("Ü", "U")
                .Replace("ü", "u")
                .Replace("ı", "i")
                .Replace("İ", "i")
                .Replace("ğ", "g")
                .Replace("Ğ", "g")
                .Replace("ß", "")
                .Replace("æ", "")
                .Replace("€", "")
                .Replace("Æ", "")
                .Replace("â", "a")
                .Replace("ê", "e")
                .Replace("î", "i")
                .Replace("Î", "i")
                .Replace("ô", "o")
                .Replace("û", "u")
                .Replace("Â", "a")
                .Replace("Ê", "e")
                .Replace("Ô", "o")
                .Replace("Û", "u")
                .Replace("ş", "s")
                .Replace("ç", "c")
                .Replace("Ç", "C")
                .Replace("<", "")
                .Replace(">", "")
                .Replace("|", "")
                .Replace(" ", "_");
        
    }
}
